import { useState, useEffect } from 'react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

export default function App() {
  const [logs, setLogs] = useState([]);
  const [alerts, setAlerts] = useState([]);
  const [chartData, setChartData] = useState([]);
  const [search, setSearch] = useState('');

  const fetchDashboardData = async () => {
    try {
      const query = search ? `?keyword=${search}` : '';
      const res = await fetch(`http://localhost:8000/api/logs${query}`);
      const data = await res.json();
      
      setLogs(data.logs || []);
      setAlerts(data.alerts || []);
      
      // Process logs into time-series data for Recharts
      const timeMap = {};
      (data.logs || []).forEach(log => {
        const timeObj = new Date(log.timestamp);
        // Group by minute
        const timeKey = `${timeObj.getHours().toString().padStart(2, '0')}:${timeObj.getMinutes().toString().padStart(2, '0')}`;
        
        if (!timeMap[timeKey]) timeMap[timeKey] = { time: timeKey, INFO: 0, ERROR: 0, WARN: 0, CRITICAL: 0 };
        timeMap[timeKey][log.level] += 1;
      });
      
      const formattedChartData = Object.values(timeMap).sort((a, b) => a.time.localeCompare(b.time));
      setChartData(formattedChartData);
    } catch (err) {
      console.error("Failed to fetch data", err);
    }
  };

  useEffect(() => {
    fetchDashboardData();
    const interval = setInterval(fetchDashboardData, 2000);
    return () => clearInterval(interval);
  }, [search]);

  // UI Tester Function
  const injectMockLog = async (level) => {
    await fetch('http://localhost:8000/api/ingest', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ level, service: 'auth-service', message: `Mock ${level} log generated by UI` })
    });
    fetchDashboardData();
  };

  const getLogColor = (level) => {
    switch(level) {
      case 'CRITICAL': return '#dc2626'; // Red
      case 'ERROR': return '#f97316'; // Orange
      case 'WARN': return '#eab308'; // Yellow
      case 'INFO': return '#3b82f6'; // Blue
      default: return '#94a3b8';
    }
  };

  return (
    <div style={{ padding: '2rem', maxWidth: '1400px', margin: '0 auto' }}>
      <header style={{ borderBottom: '1px solid #1e293b', paddingBottom: '1rem', marginBottom: '2rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1 style={{ margin: 0, fontSize: '24px', display: 'flex', alignItems: 'center', gap: '10px' }}>
            📊 InsightForge
            <span style={{ fontSize: '12px', backgroundColor: '#064e3b', color: '#34d399', padding: '2px 8px', borderRadius: '12px' }}>Live ES Sink</span>
          </h1>
        </div>
        <div style={{ display: 'flex', gap: '10px' }}>
          <button onClick={() => injectMockLog('INFO')} style={{ padding: '8px 16px', background: '#1e3a8a', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>+ INFO</button>
          <button onClick={() => injectMockLog('ERROR')} style={{ padding: '8px 16px', background: '#9a3412', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>+ ERROR</button>
          <button onClick={() => injectMockLog('CRITICAL')} style={{ padding: '8px 16px', background: '#7f1d1d', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>+ CRITICAL</button>
        </div>
      </header>

      <div style={{ display: 'grid', gridTemplateColumns: '3fr 1fr', gap: '2rem' }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
          {/* Chart Section */}
          <div style={{ backgroundColor: '#0f172a', padding: '1.5rem', borderRadius: '8px', border: '1px solid #1e293b' }}>
            <h3 style={{ margin: '0 0 1rem 0', color: '#cbd5e1' }}>Log Ingestion Volume</h3>
            <div style={{ height: '250px' }}>
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={chartData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
                  <XAxis dataKey="time" stroke="#64748b" />
                  <YAxis stroke="#64748b" />
                  <Tooltip contentStyle={{ backgroundColor: '#020617', border: '1px solid #1e293b' }} />
                  <Line type="monotone" dataKey="INFO" stroke="#3b82f6" strokeWidth={2} dot={false} />
                  <Line type="monotone" dataKey="ERROR" stroke="#f97316" strokeWidth={2} dot={false} />
                  <Line type="monotone" dataKey="CRITICAL" stroke="#dc2626" strokeWidth={2} dot={false} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Terminal Section */}
          <div style={{ backgroundColor: '#0f172a', padding: '1.5rem', borderRadius: '8px', border: '1px solid #1e293b' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '1rem' }}>
              <h3 style={{ margin: 0, color: '#cbd5e1' }}>Live Stream</h3>
              <input 
                type="text" 
                placeholder="Search logs..." 
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                style={{ padding: '4px 12px', borderRadius: '4px', border: '1px solid #334155', background: '#1e293b', color: 'white' }}
              />
            </div>
            <div style={{ backgroundColor: '#020617', padding: '1rem', borderRadius: '6px', fontFamily: 'monospace', height: '400px', overflowY: 'auto' }}>
              {logs.length === 0 ? <span style={{ color: '#475569' }}>Awaiting logs...</span> : null}
              {logs.map((log, i) => (
                <div key={i} style={{ marginBottom: '8px', fontSize: '13px', borderBottom: '1px solid #1e293b', paddingBottom: '4px' }}>
                  <span style={{ color: '#475569' }}>[{new Date(log.timestamp).toLocaleTimeString()}]</span>{' '}
                  <span style={{ color: getLogColor(log.level), fontWeight: 'bold' }}>[{log.level}]</span>{' '}
                  <span style={{ color: '#cbd5e1' }}>{log.service}:</span>{' '}
                  <span style={{ color: '#94a3b8' }}>{log.message}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Alerts Sidebar */}
        <div style={{ backgroundColor: '#0f172a', padding: '1.5rem', borderRadius: '8px', border: '1px solid #1e293b', height: 'fit-content' }}>
          <h3 style={{ margin: '0 0 1rem 0', color: '#cbd5e1' }}>Active Alerts</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {alerts.length === 0 ? <span style={{ color: '#475569', fontSize: '14px' }}>No active alerts.</span> : null}
            {alerts.map((alert, i) => (
              <div key={i} style={{ padding: '10px', backgroundColor: '#450a0a', borderLeft: '4px solid #ef4444', borderRadius: '4px', fontSize: '13px' }}>
                <div style={{ fontWeight: 'bold', color: '#fca5a5', marginBottom: '4px' }}>{alert.trigger}</div>
                <div style={{ color: '#f87171' }}>{alert.service}</div>
                <div style={{ color: '#fca5a5', marginTop: '4px', fontSize: '12px' }}>{alert.detail}</div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
